#!/bin/sh
# $OpenBSD: Xsetup_0,v 1.5 2018/07/17 11:52:12 matthieu Exp $
xsetroot -solid black
DUAL=`xrandr | awk '{print $1}' | grep VGA-1`
if [ !  -z  $DUAL ]; then
        xrandr --output VGA-1 --mode 1920x1080 --output eDP-1 --mode 1920x1080 --same-as VGA-1
fi

# sxpm OpenBSD.xpm &
